// Generated from src/assets/emoji/*.svg (kept in sync by stickers.test.ts). A flat name list, exempt from the file-size limit.
export const STICKER_NAMES = [
  'airplane',
  'automobile',
  'bell',
  'bullseye',
  'calendar',
  'check_mark_button',
  'clapper_board',
  'compass',
  'counterclockwise_arrows_button',
  'credit_card',
  'desktop_computer',
  'fire',
  'gear',
  'graduation_cap',
  'high_voltage',
  'hot_beverage',
  'house',
  'house_with_garden',
  'label',
  'link',
  'mobile_phone',
  'money_bag',
  'open_book',
  'paw_prints',
  'pig_face',
  'pill',
  'pot_of_food',
  'pushpin',
  'receipt',
  'red_heart',
  'shopping_bags',
  'steaming_bowl',
  'stethoscope',
  't_shirt',
  'timer_clock',
  'video_game',
  'wrapped_gift',
  'wrench',
] as const;

export type StickerName = (typeof STICKER_NAMES)[number];
